services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - net
    volumes:
      - db:/var/lib/mysql
  
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - net
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    networks:
      - net
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb

networks:
  net:

volumes:
  wp:
    driver_opts:
      device: /home/rjaanit/data/wp
      type: none
      o: bind
  db:
    driver_opts:
      device: /home/rjaanit/data/db
      type: none
      o: bind